# Site settings
title: Priyanka Kotnis
twitter_username: 
name: Priyaka Kotnis

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: TBD
 - title: GitHub
   url: https://github.com/priyankakotnis
 - title: StackOverflow
   url: TBD
 - title: DZone
   url: TBD
 - title: LinkedIn
   url: https://uk.linkedin.com/in/priyankakotnis

#Any buzzword skills you want to include
skills:
 - Maven
 - Spring Core
 - Spring Boot
 - Java 6-8
 - SQL
 - SOAP
 - REST
 - Design Patterns

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: TBD

#Work experience is required
roles:
 - title: Senior Software Developer
   start: Dec-2012
   end: Sept-2015
   employer: Datamatics Global Services Limited - for BUPA
   description: Agile Development
 - title: Middleware Support Specialist/DevOps
   start: May-2009
   end: Oct-2012
   employer: Datamatics Global Services Limited - for BUPA
   description: 
 - title: Software Developer
   start: July-2007
   end: Apr-2009
   employer: Datamatics Global Services Limited - Various clients
   description:

#Education is required
education:
 - level: Masters of Engineering
   date: 2016 - Awaiting final results
   subject: Software Engineering
   school: City - University of London
 - level: Bachelor of Engineering
   date: 2007
   subject: Electronics and Telecommunications
   school: University of Mumbai

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org - TBD
   courses:
   # - title: Functional Programming Principles in Scala
    #  link: https://www.coursera.org/course/progfun
     # optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      #date: September 16, 2013
   
#List of interesting Github repo/projects to include - optional
github: priyankakotnis/projects/msc-dissertation/spark-trident-bash-ansible

#Stackoverflow flair is optional
stackoverflow:
   profileurl: TBD
   flairimageurl: TBD

#Mobile apps section is optional
apps: TBD


#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: TBD
  
